In [308]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [309]:
df=pd.read_csv('/content/bank-full.csv',sep=';')

In [310]:
df.head(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
5,35,management,married,tertiary,no,231,yes,no,unknown,5,may,139,1,-1,0,unknown,no
6,28,management,single,tertiary,no,447,yes,yes,unknown,5,may,217,1,-1,0,unknown,no
7,42,entrepreneur,divorced,tertiary,yes,2,yes,no,unknown,5,may,380,1,-1,0,unknown,no
8,58,retired,married,primary,no,121,yes,no,unknown,5,may,50,1,-1,0,unknown,no
9,43,technician,single,secondary,no,593,yes,no,unknown,5,may,55,1,-1,0,unknown,no

In [311]:
for i in ['default','housing','loan']:
  df[i]=df[i].map({'no':0,'yes':1})

In [312]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,0,2143,1,0,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,0,29,1,0,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,0,2,1,1,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,0,1506,1,0,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,0,1,0,0,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,0,825,0,0,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,0,1729,0,0,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,0,5715,0,0,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,0,668,0,0,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,0,2971,0,0,cellular,17,nov,361,2,188,11,other,no

In [313]:
from sklearn.preprocessing import StandardScaler
num = ['age','balance','duration','campaign','previous']
scaler = StandardScaler()
df[num] = scaler.fit_transform(df[num])

In [314]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,1.606965,management,married,tertiary,0,0.256419,1,0,unknown,5,may,0.011016,-0.569351,-1,-0.251940,unknown,no
1,0.288529,technician,single,secondary,0,-0.437895,1,0,unknown,5,may,-0.416127,-0.569351,-1,-0.251940,unknown,no
2,-0.747384,entrepreneur,married,secondary,0,-0.446762,1,1,unknown,5,may,-0.707361,-0.569351,-1,-0.251940,unknown,no
3,0.571051,blue-collar,married,unknown,0,0.047205,1,0,unknown,5,may,-0.645231,-0.569351,-1,-0.251940,unknown,no
4,-0.747384,unknown,single,unknown,0,-0.447091,0,0,unknown,5,may,-0.233620,-0.569351,-1,-0.251940,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.947747,technician,married,tertiary,0,-0.176460,0,0,cellular,17,nov,2.791329,0.076230,-1,-0.251940,unknown,yes
45207,2.831227,retired,divorced,primary,0,0.120447,0,0,cellular,17,nov,0.768224,-0.246560,-1,-0.251940,unknown,yes
45208,2.925401,retired,married,secondary,0,1.429593,0,0,cellular,17,nov,3.373797,0.721811,184,1.050473,success,yes
45209,1.512791,blue-collar,married,secondary,0,-0.228024,0,0,telephone,17,nov,0.970146,0.399020,-1,-0.251940,unknown,no
45210,-0.370689,entrepreneur,married,secondary,0,0.528364,0,0,cellular,17,nov,0.399328,-0.246560,188,4.523577,other,no

In [315]:
df['last_contact-days']=(df['pdays']!=-1).astype(int)
df['pdays_value'] = df['pdays'].apply(lambda x: 0 if x == -1 else x)

In [316]:
df[['pdays_value']]=scaler.fit_transform(df[['pdays_value']])

In [317]:
df['job'] = df['job'].astype('category').cat.codes
df['marital'] = df['marital'].astype('category').cat.codes
df['education'] = df['education'].astype('category').cat.codes
df['poutcome']=df['poutcome'].astype('category').cat.codes

In [318]:
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y,last_contact-days,pdays_value
0,1.606965,4,1,2,0,0.256419,1,0,unknown,5,may,0.011016,-0.569351,-1,-0.251940,3,no,0,-0.411009
1,0.288529,9,2,1,0,-0.437895,1,0,unknown,5,may,-0.416127,-0.569351,-1,-0.251940,3,no,0,-0.411009
2,-0.747384,2,1,1,0,-0.446762,1,1,unknown,5,may,-0.707361,-0.569351,-1,-0.251940,3,no,0,-0.411009
3,0.571051,1,1,3,0,0.047205,1,0,unknown,5,may,-0.645231,-0.569351,-1,-0.251940,3,no,0,-0.411009
4,-0.747384,11,2,3,0,-0.447091,0,0,unknown,5,may,-0.233620,-0.569351,-1,-0.251940,3,no,0,-0.411009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,0.947747,9,1,2,0,-0.176460,0,0,cellular,17,nov,2.791329,0.076230,-1,-0.251940,3,yes,0,-0.411009
45207,2.831227,5,0,0,0,0.120447,0,0,cellular,17,nov,0.768224,-0.246560,-1,-0.251940,3,yes,0,-0.411009
45208,2.925401,5,1,1,0,1.429593,0,0,cellular,17,nov,3.373797,0.721811,184,1.050473,2,yes,1,1.432835
45209,1.512791,1,1,1,0,-0.228024,0,0,telephone,17,nov,0.970146,0.399020,-1,-0.251940,3,no,0,-0.411009
45210,-0.370689,2,1,1,0,0.528364,0,0,cellular,17,nov,0.399328,-0.246560,188,4.523577,1,no,1,1.472919

In [319]:
df['y']=df['y'].map({'no':0,'yes':1})

In [320]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.25, random_state=746, stratify=df['y'])

In [321]:
import torch
from torch import nn
abdcpp_train = torch.tensor(train_df[['age','balance','duration','campaign','previous','pdays_value']].values, dtype=torch.float32)
dhll_train = torch.tensor(train_df[['default','housing','loan','last_contact-days']].values, dtype=torch.float32)
jobs_train = torch.tensor(train_df['job'].values, dtype=torch.long)
shadi_train = torch.tensor(train_df['marital'].values, dtype=torch.long)
edu_train = torch.tensor(train_df['education'].values, dtype=torch.long)
out_train = torch.tensor(train_df['poutcome'].values, dtype=torch.long)
y_train = torch.tensor(train_df['y'].values, dtype=torch.float32)

In [322]:
abdcpp_test = torch.tensor(test_df[['age','balance','duration','campaign','previous','pdays_value']].values, dtype=torch.float32)
dhll_test = torch.tensor(test_df[['default','housing','loan','last_contact-days']].values, dtype=torch.float32)
jobs_test = torch.tensor(test_df['job'].values, dtype=torch.long)
shadi_test = torch.tensor(test_df['marital'].values, dtype=torch.long)
edu_test = torch.tensor(test_df['education'].values, dtype=torch.long)
out_test = torch.tensor(test_df['poutcome'].values, dtype=torch.long)
y_test = torch.tensor(test_df['y'].values, dtype=torch.float32)

In [323]:
class Model(nn.Module):
  def __init__(self,j,s,e,o):
    super().__init__()
    self.j_emb = nn.Embedding(j, 6)
    self.s_emb = nn.Embedding(s, 2)
    self.e_emb = nn.Embedding(e, 2)
    self.o_emb = nn.Embedding(o, 2)
    inn=6+2+2+2+6+4
    self.layer=nn.Sequential(
        nn.Linear(inn,32),
        nn.ReLU(),
        nn.Linear(32,64),
        nn.ReLU(),
        nn.Linear(64,8),
        nn.ReLU(),
        nn.Linear(8,1)
    )
  def forward(self,abdcpp,dhll,jobs,shadi,edu,out):
    j = self.j_emb(jobs)
    s = self.s_emb(shadi)
    e = self.e_emb(edu)
    o = self.o_emb(out)
    x = torch.cat([abdcpp, dhll, j, s, e, o], dim=1)
    return self.layer(x)

In [324]:
model=Model(
    j=len(df['job'].unique()),
    s=len(df['marital'].unique()),
    e=len(df['education'].unique()),
    o=len(df['poutcome'].unique())
)

In [325]:
model

Model(
  (j_emb): Embedding(12, 6)
  (s_emb): Embedding(3, 2)
  (e_emb): Embedding(4, 2)
  (o_emb): Embedding(4, 2)
  (layer): Sequential(
    (0): Linear(in_features=22, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=8, bias=True)
    (5): ReLU()
    (6): Linear(in_features=8, out_features=1, bias=True)
  )
)

In [326]:
poss = y_train.sum()
neg = len(y_train) - poss
pos = torch.tensor([neg / poss], dtype=torch.float32)
lossf = nn.BCEWithLogitsLoss(pos_weight=pos)
opt = torch.optim.Adam(model.parameters(), 0.001)
sch = torch.optim.lr_scheduler.StepLR(opt, 100, 0.9)

In [327]:
from sklearn.metrics import accuracy_score
torch.manual_seed(456)
lambda_l1 = 1e-5
epochs = 301

for epoch in range(epochs):
    model.train()
    preds = model(abdcpp_train, dhll_train, jobs_train, shadi_train, edu_train, out_train).squeeze()
    loss = lossf(preds, y_train)
    l1_penalty = sum(torch.sum(torch.abs(p)) for p in model.parameters())
    loss = loss + lambda_l1 * l1_penalty
    opt.zero_grad()
    loss.backward()
    opt.step()

    train_loss = loss.item()

    model.eval()
    with torch.no_grad():
        test_logits = model(abdcpp_test, dhll_test, jobs_test, shadi_test, edu_test, out_test).squeeze()
        test_probs = torch.sigmoid(test_logits)
        test_loss = lossf(test_logits, y_test).item()
        pred_labels = (test_probs >= 0.6).int().numpy()
        acc = accuracy_score(y_test.numpy(), pred_labels)

    sch.step()
    if epoch % 100 == 0:
        print(f"Epoch {epoch+1:02d}/{epochs} | "
              f"Train Loss: {train_loss:.4f} | "
              f"Test Loss: {test_loss:.4f} | "
              f"Test Acc: {acc:.4f} | "
              f"LR: {sch.get_last_lr()[0]:.5f}")

Epoch 01/301 | Train Loss: 1.2449 | Test Loss: 1.2363 | Test Acc: 0.8820 | LR: 0.00100
Epoch 101/301 | Train Loss: 0.7693 | Test Loss: 0.7477 | Test Acc: 0.8483 | LR: 0.00090
Epoch 201/301 | Train Loss: 0.7176 | Test Loss: 0.7167 | Test Acc: 0.8404 | LR: 0.00081
Epoch 301/301 | Train Loss: 0.6984 | Test Loss: 0.7118 | Test Acc: 0.8410 | LR: 0.00073

In [328]:
from sklearn.metrics import classification_report
model.eval()
y_true, y_pred = [], []
with torch.no_grad():
    test_logits = model(abdcpp_test, dhll_test, jobs_test, shadi_test, edu_test, out_test).squeeze()
    test_loss = lossf(test_logits, y_test).item()
    test_probs = torch.sigmoid(test_logits)
    pred_labels = (test_probs >= 0.6).int().numpy()
    y_true = y_test.numpy()
    y_pred = pred_labels

print(f"Final Test Loss: {test_loss:.4f}")
print(classification_report(y_true, y_pred, target_names=["no", "yes"]))

Final Test Loss: 0.7118
              precision    recall  f1-score   support

          no       0.97      0.85      0.90      9981
         yes       0.41      0.79      0.54      1322

    accuracy                           0.84     11303
   macro avg       0.69      0.82      0.72     11303
weighted avg       0.90      0.84      0.86     11303